# Copyright 2022 Anuket, Intel Corporation, and The Linux Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: Pod
metadata:
  name: userspace-rapid-pod-t1-p1
  annotations:
    k8s.v1.cni.cncf.io/networks: userspace-ovs-net, userspace-ovs-net
spec:
  containers:
  - name: ovs-vhost
    image: opnfv/rapid:latest
    imagePullPolicy: Never
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podinfo
      readOnly: false
    - mountPath: /usrspcni/
      name: shared-dir
    - mountPath: /opt/prox/
      name: prox-dir
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        cpu: "6000m"
        memory: "4000Mi"
        hugepages-1Gi: 4Gi
      limits:
        cpu: "6000m"
        memory: "4000Mi"
        hugepages-1Gi: 4Gi
  nodeSelector:
    vswitch: ovs
  volumes:
  - name: podinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
  - name: shared-dir
    hostPath:
      path: /var/lib/cni/usrspcni/data/
  - name: prox-dir
    hostPath:
      path: /opt/prox/
  - name: hugepage
    emptyDir:
      medium: HugePages
