# daemonset, deployment
kind: Deployment

# Nodes to deploy on
nodeSelector:
  # matchLables:
  #   key1: value1
  #   key2: value2

# multus
metacniType: multus
extraInterfaces:
  net-attach-def1
  net-attach-def2

replicas: 1

service: 
  type: NodePort
  port: 8081